# 베이스 이미지를 선택 (예: Python 3.10)
FROM python:3.10

# 작업 디렉토리 설정
WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg

RUN apt-get update && apt-get install -y lilypond

# 필요한 의존성 복사
COPY requirements.txt .

# 의존성 설치
RUN pip install --upgrade pip \
    && pip install --default-timeout=300 -r requirements.txt



# 애플리케이션 코드 복사
COPY . .

# 서버 실행
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
