# Generated by Django 4.2.13 on 2024-05-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3_file', models.FileField(blank=True, null=True, upload_to='mp3s/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
