# Generated by Django 4.2.15 on 2024-08-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
